version: '2'
services:
  conceptnet:
    build: '.'
    image: rspeer/conceptnet:5.5b1
    command: ["bash", "scripts/build.sh"]
    environment:
      - CONCEPTNET_BUILD_DATA=/data/conceptnet
    volumes:
      - cn5data:/data/conceptnet

volumes:
  cn5data:
